<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.paicbd</groupId>
    <artifactId>smsc-utils</artifactId>
    <version>3.1.0-SNAPSHOT</version>
    <name>smsc-utils</name>
    <description>Utility Module for SMSC</description>
    <licenses>
        <license>
            <name>GNU Affero General Public License</name>
            <url>http://www.gnu.org/licenses/agpl-3.0.html</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <developers>
        <developer>
            <name>Enmanuel Calero</name>
            <email>enmanuel.calero@paicbd.com</email>
            <organization>PAiC BD</organization>
            <organizationUrl>https://paic-bd.com/</organizationUrl>
            <timezone>-6</timezone>
        </developer>
        <developer>
            <name>Obed Navarrete</name>
            <email>obed.navarrete@paicbd.com</email>
            <organization>PAiC BD</organization>
            <organizationUrl>https://paicbd.com</organizationUrl>
            <timezone>-6</timezone>
        </developer>
        <developer>
            <name>Melvin Mendoza</name>
            <email>melvin.mendoza@paicbd.com</email>
            <organization>PAiC BD</organization>
            <organizationUrl>https://paic-bd.com/</organizationUrl>
            <timezone>-6</timezone>
        </developer>
        <developer>
            <name>Roberto Calero</name>
            <email>roberto.calero@paicbd.com</email>
            <organization>PAiC BD</organization>
            <organizationUrl>https://paic-bd.com/</organizationUrl>
            <timezone>-6</timezone>
        </developer>
    </developers>
    <properties>
        <java.version>21</java.version>
        <redis.clients.version>5.0.2</redis.clients.version>
        <jsmpp.version>3.1.5</jsmpp.version>
        <ss7.version>8.3.0-275</ss7.version>
        <mockito.core.version>5.12.0</mockito.core.version>
        <mockito.junit.jupiter.version>5.12.0</mockito.junit.jupiter.version>
        <junit.jupiter.version>5.10.3</junit.jupiter.version>
        <bean.matchers.version>0.14</bean.matchers.version>
        <jacoco.version>0.8.12</jacoco.version>
        <webflux.version>3.3.5</webflux.version>
        <reactor.test.version>3.7.0</reactor.test.version>
        <apache.cassandra.version>4.19.0</apache.cassandra.version>
        <spring.kafka.version>3.3.7</spring.kafka.version>
        <jackson.version>2.18.1</jackson.version>
        <bucket4j.version>8.1.0</bucket4j.version>
    </properties>
    <distributionManagement>
        <repository>
            <id>paicbd</id>
            <name>localhost-releases</name>
            <url>https://repository.ws-paicbd.com/artifactory/libs-release-local</url>
        </repository>
        <snapshotRepository>
            <id>snapshots</id>
            <name>localhost-snapshots</name>
            <url>https://repository.ws-paicbd.com/artifactory/libs-release-local</url>
        </snapshotRepository>
    </distributionManagement>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>${jackson.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.34</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.jsmpp</groupId>
            <artifactId>jsmpp</artifactId>
            <version>${jsmpp.version}</version>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>${redis.clients.version}</version>
        </dependency>
        <dependency>
            <artifactId>map-api</artifactId>
            <groupId>org.restcomm.protocols.ss7.map</groupId>
            <version>${ss7.version}</version>
        </dependency>
        <dependency>
            <groupId>org.restcomm.protocols.ss7.map</groupId>
            <artifactId>map-impl</artifactId>
            <version>${ss7.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco-maven-plugin</artifactId>
            <version>${jacoco.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.cassandra</groupId>
            <artifactId>java-driver-core</artifactId>
            <version>${apache.cassandra.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
            <version>${spring.kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.cassandra</groupId>
            <artifactId>java-driver-query-builder</artifactId>
            <version>${apache.cassandra.version}</version>
        </dependency>
        <!-- TESTING DEPENDENCIES -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>3.2.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${mockito.core.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <version>${mockito.junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
            <version>${webflux.version}</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <version>${reactor.test.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-xml</artifactId>
        </dependency>
        <dependency>
            <groupId>com.bucket4j</groupId>
            <artifactId>bucket4j-core</artifactId>
            <version>${bucket4j.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.17.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>set</goal>
                            <goal>commit</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.3.1</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                    </includes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <classifier>exec</classifier>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.sonarsource.scanner.maven</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
                <version>4.0.0.4121</version>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.12</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
